# Generated by Django 5.2.5 on 2025-08-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galery',
            old_name='ingredients',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='galery',
            old_name='instructions',
            new_name='photo_location',
        ),
        migrations.RemoveField(
            model_name='galery',
            name='cooking_time',
        ),
        migrations.AddField(
            model_name='galery',
            name='photo_period',
            field=models.IntegerField(default=30, help_text='Em dias'),
            preserve_default=False,
        ),
    ]
