# Generated by Django 5.2.5 on 2025-08-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_rename_ingredients_galery_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galery',
            options={'verbose_name_plural': 'Galleries'},
        ),
        migrations.AddField(
            model_name='galery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='galleries/'),
        ),
    ]
