# Generated by Django 5.2.5 on 2025-08-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_alter_galery_options_galery_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galery',
            options={'verbose_name_plural': 'galleries'},
        ),
    ]
